apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fenix-nfe-api-hpa
  namespace: fenix-nfe
  labels:
    app: nfe-api
    component: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fenix-nfe-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: nfe_requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
  - type: Pods
    pods:
      metric:
        name: nfe_queue_depth
      target:
        type: AverageValue
        averageValue: "50"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fenix-nfe-api-hpa-queue
  namespace: fenix-nfe
  labels:
    app: nfe-api
    component: hpa-queue
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fenix-nfe-api
  minReplicas: 2
  maxReplicas: 50
  metrics:
  - type: External
    external:
      metric:
        name: rabbitmq_queue_messages
        selector:
          matchLabels:
            queue: "nfe.emitir.normal"
      target:
        type: AverageValue
        averageValue: "100"
  - type: External
    external:
      metric:
        name: rabbitmq_queue_messages
        selector:
          matchLabels:
            queue: "nfe.emitir.high"
      target:
        type: AverageValue
        averageValue: "20"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 5
        periodSeconds: 120
      - type: Pods
        value: 1
        periodSeconds: 120
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 10
        periodSeconds: 30
      selectPolicy: Max
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: fenix-nfe-api-metrics
  namespace: fenix-nfe
  labels:
    app: nfe-api
    component: metrics
spec:
  selector:
    matchLabels:
      app: nfe-api
      component: api
  endpoints:
  - port: management
    path: /actuator/prometheus
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: fenix-nfe-api-custom-metrics
  namespace: fenix-nfe
  labels:
    app: nfe-api
    component: custom-metrics
spec:
  selector:
    matchLabels:
      app: nfe-api
      component: api
  endpoints:
  - port: management
    path: /actuator/prometheus
    interval: 15s
    scrapeTimeout: 5s
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'nfe_.*'
      action: keep
