apiVersion: batch/v1
kind: Job
metadata:
  name: fenix-nfe-migration
  namespace: fenix-nfe
  labels:
    app: nfe-migration
    version: v1.0.0
spec:
  template:
    metadata:
      labels:
        app: nfe-migration
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: fenix-nfe-api:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Iniciando migração do banco de dados..."
          # Executar migrações Flyway
          kubectl exec -n fenix-nfe deployment/fenix-nfe-api -- curl -X POST http://localhost:8080/actuator/migrate
          echo "Migração concluída com sucesso"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
  backoffLimit: 3
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fenix-nfe-data-seed
  namespace: fenix-nfe
  labels:
    app: nfe-data-seed
    version: v1.0.0
spec:
  template:
    metadata:
      labels:
        app: nfe-data-seed
    spec:
      restartPolicy: Never
      containers:
      - name: data-seed
        image: fenix-nfe-api:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Iniciando seed de dados iniciais..."
          # Executar seed de dados
          kubectl exec -n fenix-nfe deployment/fenix-nfe-api -- curl -X POST http://localhost:8080/actuator/seed
          echo "Seed de dados concluído com sucesso"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
  backoffLimit: 3
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fenix-nfe-test
  namespace: fenix-nfe
  labels:
    app: nfe-test
    version: v1.0.0
spec:
  template:
    metadata:
      labels:
        app: nfe-test
    spec:
      restartPolicy: Never
      containers:
      - name: test
        image: fenix-nfe-api:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Iniciando testes de integração..."
          # Executar testes
          kubectl exec -n fenix-nfe deployment/fenix-nfe-api -- curl -X POST http://localhost:8080/actuator/test/integration
          echo "Testes concluídos com sucesso"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
  backoffLimit: 1
