apiVersion: v1
kind: Namespace
metadata:
  name: fenix-nfe
  labels:
    name: fenix-nfe
    app: nfe-api
    environment: production
    team: fenix
    version: "1.0.0"
  annotations:
    description: "Namespace para a API de NFe do sistema Fenix"
    contact: "dev@fenix.com.br"
    created-by: "Fenix Team"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: fenix-nfe-quota
  namespace: fenix-nfe
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "20"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: fenix-nfe-limits
  namespace: fenix-nfe
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "50m"
      memory: "128Mi"
    type: Container
  - max:
      storage: "10Gi"
    min:
      storage: "1Gi"
    type: PersistentVolumeClaim
