apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: fenix-nfe-psp
  namespace: fenix-nfe
  labels:
    app: nfe-api
    version: v1.0.0
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: true
  hostNetwork: false
  hostIPC: false
  hostPID: false
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: fenix-nfe-psp-privileged
  namespace: fenix-nfe
  labels:
    app: nfe-privileged
    version: v1.0.0
spec:
  privileged: true
  allowPrivilegeEscalation: true
  requiredDropCapabilities:
    - ALL
  volumes:
    - '*'
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  hostNetwork: true
  hostIPC: true
  hostPID: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fenix-nfe-sa
  namespace: fenix-nfe
  labels:
    app: nfe-api
    version: v1.0.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fenix-nfe-psp-user
  labels:
    app: nfe-api
    version: v1.0.0
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - fenix-nfe-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fenix-nfe-psp-user
  labels:
    app: nfe-api
    version: v1.0.0
roleRef:
  kind: ClusterRole
  name: fenix-nfe-psp-user
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fenix-nfe-sa
  namespace: fenix-nfe
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fenix-nfe-psp-privileged-user
  labels:
    app: nfe-privileged
    version: v1.0.0
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - fenix-nfe-psp-privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fenix-nfe-psp-privileged-user
  labels:
    app: nfe-privileged
    version: v1.0.0
roleRef:
  kind: ClusterRole
  name: fenix-nfe-psp-privileged-user
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fenix-nfe-sa
  namespace: fenix-nfe
