apiVersion: v1
kind: ServiceAccount
metadata:
  name: fenix-nfe-sa
  namespace: fenix-nfe
  labels:
    app: nfe-api
    component: service-account
  annotations:
    description: "Service Account para a API de NFe do sistema Fenix"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fenix-nfe-role
  namespace: fenix-nfe
  labels:
    app: nfe-api
    component: role
rules:
# Pods
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
# Services
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
# Endpoints
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
# ConfigMaps
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Secrets
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
# Events
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# PersistentVolumeClaims
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
# PersistentVolumes
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch"]
# Nodes
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
# Namespaces
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
# Deployments
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
# ReplicaSets
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
# StatefulSets
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch"]
# DaemonSets
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch"]
# HorizontalPodAutoscalers
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
# Ingresses
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
# NetworkPolicies
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch"]
# CustomResourceDefinitions
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
# ServiceMonitors
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get", "list", "watch"]
# PrometheusRules
- apiGroups: ["monitoring.coreos.com"]
  resources: ["prometheusrules"]
  verbs: ["get", "list", "watch"]
# Alertmanagers
- apiGroups: ["monitoring.coreos.com"]
  resources: ["alertmanagers"]
  verbs: ["get", "list", "watch"]
# PodMonitors
- apiGroups: ["monitoring.coreos.com"]
  resources: ["podmonitors"]
  verbs: ["get", "list", "watch"]
# Probes
- apiGroups: ["monitoring.coreos.com"]
  resources: ["probes"]
  verbs: ["get", "list", "watch"]
# ThanosRulers
- apiGroups: ["monitoring.coreos.com"]
  resources: ["thanosrulers"]
  verbs: ["get", "list", "watch"]
# ThanosQueriers
- apiGroups: ["monitoring.coreos.com"]
  resources: ["thanosqueriers"]
  verbs: ["get", "list", "watch"]
# ThanosStores
- apiGroups: ["monitoring.coreos.com"]
  resources: ["thanosstores"]
  verbs: ["get", "list", "watch"]
# ThanosReceivers
- apiGroups: ["monitoring.coreos.com"]
  resources: ["thanosreceivers"]
  verbs: ["get", "list", "watch"]
# ThanosCompactors
- apiGroups: ["monitoring.coreos.com"]
  resources: ["thanoscompactors"]
  verbs: ["get", "list", "watch"]
# ThanosSidecars
- apiGroups: ["monitoring.coreos.com"]
  resources: ["thanossidecars"]
  verbs: ["get", "list", "watch"]
# ThanosQueriers
- apiGroups: ["monitoring.coreos.com"]
  resources: ["thanosqueriers"]
  verbs: ["get", "list", "watch"]
# ThanosStores
- apiGroups: ["monitoring.coreos.com"]
  resources: ["thanosstores"]
  verbs: ["get", "list", "watch"]
# ThanosReceivers
- apiGroups: ["monitoring.coreos.com"]
  resources: ["thanosreceivers"]
  verbs: ["get", "list", "watch"]
# ThanosCompactors
- apiGroups: ["monitoring.coreos.com"]
  resources: ["thanoscompactors"]
  verbs: ["get", "list", "watch"]
# ThanosSidecars
- apiGroups: ["monitoring.coreos.com"]
  resources: ["thanossidecars"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fenix-nfe-rolebinding
  namespace: fenix-nfe
  labels:
    app: nfe-api
    component: rolebinding
subjects:
- kind: ServiceAccount
  name: fenix-nfe-sa
  namespace: fenix-nfe
roleRef:
  kind: Role
  name: fenix-nfe-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fenix-nfe-cluster-role
  labels:
    app: nfe-api
    component: cluster-role
rules:
# Nodes
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
# Namespaces
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
# PersistentVolumes
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch"]
# StorageClasses
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
# VolumeAttachments
- apiGroups: ["storage.k8s.io"]
  resources: ["volumeattachments"]
  verbs: ["get", "list", "watch"]
# CustomResourceDefinitions
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
# ServiceMonitors
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get", "list", "watch"]
# PrometheusRules
- apiGroups: ["monitoring.coreos.com"]
  resources: ["prometheusrules"]
  verbs: ["get", "list", "watch"]
# Alertmanagers
- apiGroups: ["monitoring.coreos.com"]
  resources: ["alertmanagers"]
  verbs: ["get", "list", "watch"]
# PodMonitors
- apiGroups: ["monitoring.coreos.com"]
  resources: ["podmonitors"]
  verbs: ["get", "list", "watch"]
# Probes
- apiGroups: ["monitoring.coreos.com"]
  resources: ["probes"]
  verbs: ["get", "list", "watch"]
# ThanosRulers
- apiGroups: ["monitoring.coreos.com"]
  resources: ["thanosrulers"]
  verbs: ["get", "list", "watch"]
# ThanosQueriers
- apiGroups: ["monitoring.coreos.com"]
  resources: ["thanosqueriers"]
  verbs: ["get", "list", "watch"]
# ThanosStores
- apiGroups: ["monitoring.coreos.com"]
  resources: ["thanosstores"]
  verbs: ["get", "list", "watch"]
# ThanosReceivers
- apiGroups: ["monitoring.coreos.com"]
  resources: ["thanosreceivers"]
  verbs: ["get", "list", "watch"]
# ThanosCompactors
- apiGroups: ["monitoring.coreos.com"]
  resources: ["thanoscompactors"]
  verbs: ["get", "list", "watch"]
# ThanosSidecars
- apiGroups: ["monitoring.coreos.com"]
  resources: ["thanossidecars"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fenix-nfe-cluster-rolebinding
  labels:
    app: nfe-api
    component: cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: fenix-nfe-sa
  namespace: fenix-nfe
roleRef:
  kind: ClusterRole
  name: fenix-nfe-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fenix-nfe-backup-role
  namespace: fenix-nfe
  labels:
    app: nfe-api
    component: backup-role
rules:
# Pods
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
# Services
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
# Endpoints
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
# ConfigMaps
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Secrets
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
# Events
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# PersistentVolumeClaims
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
# PersistentVolumes
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch"]
# Deployments
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
# ReplicaSets
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
# StatefulSets
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch"]
# DaemonSets
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fenix-nfe-backup-rolebinding
  namespace: fenix-nfe
  labels:
    app: nfe-api
    component: backup-rolebinding
subjects:
- kind: ServiceAccount
  name: fenix-nfe-backup-sa
  namespace: fenix-nfe
roleRef:
  kind: Role
  name: fenix-nfe-backup-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fenix-nfe-backup-sa
  namespace: fenix-nfe
  labels:
    app: nfe-api
    component: backup-service-account
  annotations:
    description: "Service Account para backup da API de NFe do sistema Fenix"
