apiVersion: v1
kind: Secret
metadata:
  name: fenix-nfe-secrets
  namespace: fenix-nfe
  labels:
    app: nfe-api
    component: secrets
type: Opaque
data:
  # Base64 encoded values
  # Use: echo -n "your-password" | base64
  db-password: cG9zdGdyZXNfcGFzc3dvcmQ=  # postgres_password
  rabbitmq-password: cmFiYml0bXFfcGFzc3dvcmQ=  # rabbitmq_password
  redis-password: cmVkaXNfcGFzc3dvcmQ=  # redis_password
  jwt-secret: eW91cl92ZXJ5X2xvbmdfYW5kX3NlY3VyZV9qd3Rfc2VjcmV0X2tleV9oZXJlX21pbmltdW1fMjU2X2JpdHM=  # your_very_long_and_secure_jwt_secret_key_here_minimum_256_bits
  jwt-refresh-secret: eW91cl92ZXJ5X2xvbmdfYW5kX3NlY3VyZV9qd3RfcmVmcmVzaF9zZWNyZXRfa2V5X2hlcmVfbWluaW11bV8yNTZfYml0cw==  # your_very_long_and_secure_jwt_refresh_secret_key_here_minimum_256_bits
  sefaz-certificate: ""  # Base64 encoded certificate
  sefaz-certificate-password: c2VmYXpfY2VydGlmaWNhdGVfcGFzc3dvcmQ=  # sefaz_certificate_password
  email-password: ZW1haWxfcGFzc3dvcmQ=  # email_password
  slack-webhook-url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvWU9VUi9TTEFDSy9XRUJIT09L  # https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
  backup-encryption-key: YmFja3VwX2VuY3J5cHRpb25fa2V5XzEyMzQ1Njc4OTA=  # backup_encryption_key_1234567890
  monitoring-token: bW9uaXRvcmluZ190b2tlbl8xMjM0NTY3ODkw  # monitoring_token_1234567890
---
apiVersion: v1
kind: Secret
metadata:
  name: fenix-nfe-tls
  namespace: fenix-nfe
  labels:
    app: nfe-api
    component: tls
type: kubernetes.io/tls
data:
  # Base64 encoded TLS certificate and key
  # Use: kubectl create secret tls fenix-nfe-tls --cert=path/to/cert.pem --key=path/to/key.pem
  tls.crt: ""  # Base64 encoded certificate
  tls.key: ""  # Base64 encoded private key
---
apiVersion: v1
kind: Secret
metadata:
  name: fenix-nfe-management-tls
  namespace: fenix-nfe
  labels:
    app: nfe-api
    component: management-tls
type: kubernetes.io/tls
data:
  # Base64 encoded TLS certificate and key for management endpoints
  tls.crt: ""  # Base64 encoded certificate
  tls.key: ""  # Base64 encoded private key
---
apiVersion: v1
kind: Secret
metadata:
  name: fenix-nfe-registry-secret
  namespace: fenix-nfe
  labels:
    app: nfe-api
    component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""  # Base64 encoded docker config json
---
apiVersion: v1
kind: Secret
metadata:
  name: fenix-nfe-backup-secret
  namespace: fenix-nfe
  labels:
    app: nfe-api
    component: backup
type: Opaque
data:
  # Backup storage credentials
  aws-access-key-id: ""  # Base64 encoded AWS access key
  aws-secret-access-key: ""  # Base64 encoded AWS secret key
  aws-region: dXMtZWFzdC0x  # us-east-1
  s3-bucket: ZmVuaXgtbmZlLWJhY2t1cHM=  # fenix-nfe-backups
  gcp-service-account: ""  # Base64 encoded GCP service account JSON
  azure-storage-account: ""  # Base64 encoded Azure storage account
  azure-storage-key: ""  # Base64 encoded Azure storage key
---
apiVersion: v1
kind: Secret
metadata:
  name: fenix-nfe-monitoring-secret
  namespace: fenix-nfe
  labels:
    app: nfe-api
    component: monitoring
type: Opaque
data:
  # Monitoring and alerting credentials
  prometheus-url: aHR0cDovL3Byb21ldGhldXM6OTA5MA==  # http://prometheus:9090
  grafana-url: aHR0cDovL2dyYWZhbmE6MzAwMA==  # http://grafana:3000
  grafana-api-key: ""  # Base64 encoded Grafana API key
  alertmanager-url: aHR0cDovL2FsZXJ0bWFuYWdlcjo5MDkz  # http://alertmanager:9093
  jaeger-url: aHR0cDovL2phZWdlcjoxNDY2OA==  # http://jaeger:16668
  elasticsearch-url: aHR0cDovL2VsYXN0aWNzZWFyY2g6OTIwMA==  # http://elasticsearch:9200
  elasticsearch-username: ""  # Base64 encoded Elasticsearch username
  elasticsearch-password: ""  # Base64 encoded Elasticsearch password
  kibana-url: aHR0cDovL2tpYmFuYTo1NjAx  # http://kibana:5601
  slack-webhook-url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvWU9VUi9TTEFDSy9XRUJIT09L  # https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
  email-smtp-host: c210cC5nbWFpbC5jb20=  # smtp.gmail.com
  email-smtp-port: NTg3  # 587
  email-smtp-username: ""  # Base64 encoded email username
  email-smtp-password: ""  # Base64 encoded email password
  email-from: YWxlcnRzQGZlbml4LmNvbS5icg==  # alerts@fenix.com.br
  email-to: YWRtaW5AZmVuaXguY29tLmJyLGRldm9wc0BmZW5peC5jb20uYnI=  # admin@fenix.com.br,devops@fenix.com.br
