#!/bin/bash

echo "🗄️ CONFIGURAÇÃO DE BANCO DE DADOS NO VERCEL"
echo "=============================================="
echo ""

echo "📋 OPÇÕES DISPONÍVEIS:"
echo "1. Neon (Recomendado) - PostgreSQL gratuito"
echo "2. Supabase - PostgreSQL + APIs extras"
echo "3. PlanetScale - MySQL (não recomendado para este projeto)"
echo ""

echo "🚀 CONFIGURAÇÃO RECOMENDADA: NEON"
echo "=================================="
echo ""
echo "1. Acesse: https://neon.tech"
echo "2. Clique em 'Sign Up'"
echo "3. Conecte com GitHub"
echo "4. Crie um novo projeto:"
echo "   - Nome: fenix-backend"
echo "   - Região: São Paulo"
echo "   - PostgreSQL: Versão 15"
echo ""

echo "🔧 VARIÁVEIS DE AMBIENTE PARA O VERCEL:"
echo "======================================="
echo ""
echo "No painel da Vercel → Settings → Environment Variables:"
echo ""
echo "# Banco de Dados"
echo "DATABASE_URL=postgresql://username:password@ep-xxx-xxx.us-east-1.aws.neon.tech/neondb?sslmode=require"
echo "DB_HOST=ep-xxx-xxx.us-east-1.aws.neon.tech"
echo "DB_PORT=5432"
echo "DB_USERNAME=username"
echo "DB_PASSWORD=password"
echo "DB_DATABASE=neondb"
echo ""
echo "# Redis (opcional)"
echo "REDIS_URL=redis://username:password@xxx.upstash.io:6379"
echo ""
echo "# CORS"
echo "CORS_ORIGIN=http://localhost:3004,https://fenixfrontendatual.vercel.app"
echo ""
echo "# JWT"
echo "JWT_SECRET=seu_jwt_secret_super_seguro_aqui"
echo "JWT_EXPIRES_IN=24h"
echo ""
echo "# Criptografia"
echo "ENCRYPTION_KEY=chave_de_criptografia_super_segura_123456789"
echo ""
echo "# Ambiente"
echo "NODE_ENV=production"
echo "PORT=3001"
echo ""

echo "🧪 TESTANDO APÓS CONFIGURAÇÃO:"
echo "=============================="
echo ""
echo "# Testar endpoint simples"
echo "curl https://fenix-backend.vercel.app/api/simple-health"
echo ""
echo "# Testar health check completo"
echo "curl https://fenix-backend.vercel.app/api/health"
echo ""

echo "✅ PRÓXIMOS PASSOS:"
echo "==================="
echo "1. Criar conta no Neon"
echo "2. Configurar variáveis no Vercel"
echo "3. Aguardar redeploy automático"
echo "4. Testar endpoints"
echo "5. Verificar logs no Vercel"
echo ""

echo "📚 DOCUMENTAÇÃO COMPLETA:"
echo "========================="
echo "Arquivo: VERCEL_DATABASE_SETUP.md"
echo ""
