# Configuração base da aplicação
spring:
  application:
    name: fenix-nfe-api
  profiles:
    active: dev

# Configuração do servidor
server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/xml,text/plain
    min-response-size: 1024

# Configuração de logging
logging:
  level:
    br.com.fenix.nfe: DEBUG
    org.springframework.amqp: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Configuração do Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99

# Configuração de cache
spring:
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutos
      cache-null-values: false

# Configuração de validação
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

# Configuração de JSON
spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      write-null-map-values: false
    deserialization:
      fail-on-unknown-properties: false

# Configuração JWT
app:
  jwt:
    secret: fenix-nfe-api-secret-key-2024-very-long-and-secure-key-for-production
    expiration: 86400000 # 24 horas
    refresh-expiration: 604800000 # 7 dias

# Configuração Swagger
app:
  swagger:
    title: Fenix NFe API
    description: API para emissão e gerenciamento de NFe com arquitetura de filas
    version: 1.0.0
    contact:
      name: Fenix Team
      email: contato@fenix.com.br
      url: https://fenix.com.br
    license:
      name: MIT License
      url: https://opensource.org/licenses/MIT
    server:
      url: http://localhost:8080
      description: Servidor de Desenvolvimento

# Configuração de segurança
app:
  security:
    cors:
      allowed-origins: 
        - http://localhost:3000
        - http://localhost:8080
        - https://*.fenix.com.br
        - https://*.icertus.com.br
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

